
sudo: required
dist: trusty
language: python

os:
  - linux

python:
  - 2.6
  - 2.7

env:
  - BUP_CC=gcc
  - BUP_CC=clang

# Because OS X doesn't support "language: python"
matrix:
  include:
    - os: osx
      language: generic
      env: BUP_CC=gcc
    - os: osx
      language: generic
      env: BUP_CC=clang

install:
  - sudo -i "$TRAVIS_BUILD_DIR/travis/prep-system"
  - "$TRAVIS_BUILD_DIR/travis/prep-system"

script:
  - ~/bup-build-env "$TRAVIS_BUILD_DIR/travis/test"
  - sudo -i ~/bup-build-env "$TRAVIS_BUILD_DIR/travis/test"
